# Generated by Django 4.2.5 on 2023-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Town'),
        ),
    ]
