# Generated by Django 4.2.5 on 2023-09-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telephone_alter_user_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
