version: '3'

services:
  postgresql:
    image: postgres
    user: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 2

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 2

  drf_gunicorn:
    build: .
    env_file:
      - .env
    volumes:
      - ./static:/static
      - .:/atom-habits
    ports:
      - '8000:8000'
    command: sh -c "poetry run python manage.py migrate &&poetry run python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:8000"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
        test: sh -c "curl -f http://localhost:8000/"
        interval: 10s
        timeout: 5s
        retries: 3

  nginx:
    image: nginx
    volumes:
      - ./static:/static
      - ./nginx/local/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - drf_gunicorn

  celery:
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    depends_on:
      drf_gunicorn:
        condition: service_healthy

  celery_beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO -S django
    depends_on:
      drf_gunicorn:
        condition: service_healthy