# Generated by Django 4.2.5 on 2023-09-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('time', models.TimeField(db_index=True, verbose_name='Time')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('is_pleasant', models.BooleanField(verbose_name='Is pleasant')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10, verbose_name='Frequency')),
                ('time_complete', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time complete')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reward')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_habits', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
