# Generated by Django 4.2.5 on 2023-09-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='pleasant_habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habits', to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_complete',
            field=models.PositiveIntegerField(verbose_name='Time complete'),
        ),
    ]
